In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
% cd drive/MyDrive    

/content/drive/MyDrive


In [ ]:

import pandas as pd
 
df = pd.read_csv("data.csv")


In [ ]:
len(df)

4964

In [ ]:
df


url1_lang url2_lang                pair_id  \
0           en        en  1484084337_1484110209   
1           en        en  1484396422_1483924666   
2           en        en  1484698254_1483758694   
3           en        en  1576314516_1576455088   
4           en        en  1484036253_1483894099   
...        ...       ...                    ...   
4959        tr        tr  1586195445_1598778991   
4960        tr        tr  1590915424_1590940388   
4961        tr        tr  1526157103_1492737005   
4962        tr        tr  1603274500_1618292937   
4963        tr        tr  1597247537_1604202164   

                                                  link1  \
0     https://www.washingtonpost.com/local/virginia-...   
1     https://www.stlucianewsonline.com/guyana-three...   
2     https://www.teaparty.org/trump-brings-in-2020-...   
3     https://gadgets.ndtv.com/apps/news/zomato-uber...   
4     https://news.yahoo.com/india-approves-third-mo...   
...                                                 ...   
4959  http://www.haberler.com/bm-aden-de-2-bini-aski...   
4960  https://www.haberler.com/kovid-19-dan-dolayi-l...   
4961  http://www.samanyoluhaber.com/saray-da-care-ol...   
4962  https://www.haberler.com/ergene-belediyesi-yol...   
4963  https://www.takvim.com.tr/guncel/2020/05/05/gr...   

                                                  link2  \
0     https://www.washingtonpost.com/world/the_ameri...   
1     https://www.thestar.com/news/world/europe/2020...   
2     https://www.timesofisrael.com/trump-says-he-do...   
3     https://gadgets.ndtv.com/internet/news/indian-...   
4     https://www.channelnewsasia.com/news/asia/indi...   
...                                                 ...   
4959  https://www.haberler.com/bm-den-yemen-de-kadin...   
4960  https://www.aksam.com.tr/spor/fabio-capello-ko...   
4961  https://www.fotomac.com.tr/besiktas/2020/01/12...   
4962  https://www.haberler.com/ergene-de-ahimehmet-v...   
4963  https://www.yeniasir.com.tr/izmir/2020/05/12/s...   

                                               ia_link1  \
0     https://web.archive.org/web/www.washingtonpost...   
1     https://web.archive.org/web/www.stlucianewsonl...   
2     https://web.archive.org/web/www.teaparty.org/t...   
3     https://web.archive.org/web/gadgets.ndtv.com/a...   
4     https://web.archive.org/web/news.yahoo.com/ind...   
...                                                 ...   
4959  https://web.archive.org/web/www.haberler.com/b...   
4960  https://web.archive.org/web/www.haberler.com/k...   
4961  https://web.archive.org/web/www.samanyoluhaber...   
4962  https://web.archive.org/web/www.haberler.com/e...   
4963  https://web.archive.org/web/www.takvim.com.tr/...   

                                               ia_link2  Geography  Entities  \
0     https://web.archive.org/web/www.washingtonpost...        4.0  4.000000   
1     https://web.archive.org/web/www.thestar.com/ne...        4.0  4.000000   
2     https://web.archive.org/web/www.timesofisrael....        1.0  2.000000   
3     https://web.archive.org/web/gadgets.ndtv.com/i...        1.0  2.333333   
4     https://web.archive.org/web/www.channelnewsasi...        1.0  1.250000   
...                                                 ...        ...       ...   
4959  https://web.archive.org/web/www.haberler.com/b...        1.0  2.000000   
4960  https://web.archive.org/web/www.aksam.com.tr/s...        1.0  1.000000   
4961  https://web.archive.org/web/www.fotomac.com.tr...        1.0  2.000000   
4962  https://web.archive.org/web/www.haberler.com/e...        1.0  2.000000   
4963  https://web.archive.org/web/www.yeniasir.com.t...        2.0  2.000000   

          Time  Narrative   Overall     Style      Tone  
0     1.000000   4.000000  4.000000  1.666667  2.000000  
1     1.000000   4.000000  3.666667  1.666667  1.333333  
2     1.000000   2.333333  2.333333  1.000000  1.333333  
3     2.666667   1.666667  2.000000  1.666667  1.666667  
4     1.000000

In [ ]:
import numpy as np
data = np.array(df['Geography']).reshape(-1,1)
data = np.append(data,np.array(df['Entities']).reshape(-1,1),axis = 1)
data = np.append(data,np.array(df['Time']).reshape(-1,1),axis = 1)
data = np.append(data,np.array(df['Narrative']).reshape(-1,1),axis = 1)
data = np.append(data,np.array(df['Style']).reshape(-1,1),axis = 1)
data = np.append(data,np.array(df['Tone']).reshape(-1,1),axis = 1)


In [ ]:
data = (data - 1)/3


In [ ]:
np.shape(data)
data

array([[1.        , 1.        , 0.        , 1.        , 0.22222222,
        0.33333333],
       [1.        , 1.        , 0.        , 1.        , 0.22222222,
        0.11111111],
       [0.        , 0.33333333, 0.        , 0.44444444, 0.        ,
        0.11111111],
       ...,
       [0.        , 0.33333333, 0.66666667, 1.        , 0.        ,
        0.33333333],
       [0.        , 0.33333333, 0.66666667, 0.66666667, 0.        ,
        0.        ],
       [0.33333333, 0.33333333, 0.        , 0.33333333, 0.66666667,
        0.        ]])

In [ ]:
label = np.array(df['Overall']).reshape(-1,1)
label = label.reshape(-1,)
label = (label - 1)/3

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data, label, test_size=0.20)

In [ ]:
import torch as T
class Net(T.nn.Module):
  def __init__(self):
    super(Net, self).__init__()
    self.hid1 = T.nn.Linear(6, 10)  # 8-(10-10)-1
    self.hid2 = T.nn.Linear(10, 10)
    self.oupt = T.nn.Linear(10, 1)

    T.nn.init.xavier_uniform_(self.hid1.weight)
    T.nn.init.zeros_(self.hid1.bias)
    T.nn.init.xavier_uniform_(self.hid2.weight)
    T.nn.init.zeros_(self.hid2.bias)
    T.nn.init.xavier_uniform_(self.oupt.weight)
    T.nn.init.zeros_(self.oupt.bias)

  def forward(self, x):
    z = T.relu(self.hid1(x))
    z = T.relu(self.hid2(z))
    z = self.oupt(z)  # no activation
    return z

In [ ]:
mlp = Net()


In [ ]:

  
# Define the loss function and optimizer
loss_function = T.nn.MSELoss()
optimizer = T.optim.Adam(mlp.parameters(), lr=1e-5)
  
  # Run the training loop
for epoch in range(0, 100): # 5 epochs at maximum
    
    # Print epoch
  print(f'Starting epoch {epoch+1}')
    
    # Set current loss value
  current_loss = 0.0
    
    # Iterate over the DataLoader for training data
  for i in range(len(X_train)):
      
      # Get and prepare inputs
    inputs = T.tensor((X_train[i:i+1,:]).astype(np.float32))
    targets = T.tensor((y_train[i]).astype(np.float32))
      
      # Zero the gradients
    optimizer.zero_grad()
      
      # Perform forward pass
    outputs = mlp(inputs)
      
      # Compute loss
    loss = loss_function(outputs, targets)
      
      # Perform backward pass
    loss.backward()
      
      # Perform optimization
    optimizer.step()
      
      # Print statistics
    current_loss += loss.item()
      
    
  print(current_loss / len(X_train)) 

  # Process is complete.
print('Training process has finished.')

Starting epoch 1


/usr/local/lib/python3.7/dist-packages/torch/nn/modules/loss.py:520: UserWarning: Using a target size (torch.Size([])) that is different to the input size (torch.Size([1, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


0.02163469070745417
Starting epoch 2
0.02157753350076403
Starting epoch 3
0.021534595556441424
Starting epoch 4
0.02149775617101359
Starting epoch 5
0.02146470734710536
Starting epoch 6
0.021434609406352154
Starting epoch 7
0.02140677887016221
Starting epoch 8
0.021380878818276022
Starting epoch 9
0.021356725018160543
Starting epoch 10
0.021334059812490723
Starting epoch 11
0.021312573955525424
Starting epoch 12
0.021292241579860906
Starting epoch 13
0.021272909094165328
Starting epoch 14
0.021254474325022022
Starting epoch 15
0.021236827859725724
Starting epoch 16
0.021219891163197408
Starting epoch 17
0.02120358445809507
Starting epoch 18
0.02118786043359441
Starting epoch 19
0.02117269033579061
Starting epoch 20
0.021158019635123468
Starting epoch 21
0.021143803927813547
Starting epoch 22
0.021130016624862982
Starting epoch 23
0.021116629780108843
Starting epoch 24
0.021103620062810143
Starting epoch 25
0.02109097296118201
Starting epoch 26
0.021078675876502796
Starting epoch 27
0.0

In [ ]:
#Saving the model 
import pickle
with open('NN_model', 'wb') as files:
    pickle.dump(mlp, files)

In [ ]:
#Testing 
mlp(T.tensor((data[19:20,:]).astype(np.float32)))

tensor([[-0.1208]], grad_fn=<AddmmBackward0>)

In [ ]:
#Testing

test_pred = mlp(T.tensor(X_test.astype(np.float32)))
loss_f = T.nn.MSELoss()
loss = 0
for i in range(len(test_pred)):
    loss = loss + loss_f(test_pred[i],T.tensor(y_test[i])).item()

print(loss/len(test_pred))

0.02237902697198646


/usr/local/lib/python3.7/dist-packages/torch/nn/modules/loss.py:520: UserWarning: Using a target size (torch.Size([])) that is different to the input size (torch.Size([1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


In [ ]:
#Evaluation 

df = pd.read_csv("final_evaluation_data.csv")
eval = np.array(df['GEO']).reshape(-1,1)
eval = np.append(eval,np.array(df['ENT']).reshape(-1,1),axis = 1)
eval = np.append(eval,np.array(df['TIME']).reshape(-1,1),axis = 1)
eval = np.append(eval,np.array(df['NAR']).reshape(-1,1),axis = 1)
eval = np.append(eval,np.array(df['STYLE']).reshape(-1,1),axis = 1)
eval = np.append(eval,np.array(df['TONE']).reshape(-1,1),axis = 1)
eval = (eval - 1)/3
label = np.array(df['Overall']).reshape(-1,1)
label = label.reshape(-1,)
label = (label-1)/3

In [ ]:
pred = mlp(T.tensor(eval.astype(np.float32)))

In [ ]:
pred

tensor([[0.9726],
        [0.1007],
        [0.9726],
        ...,
        [0.9726],
        [0.0821],
        [0.1769]], grad_fn=<AddmmBackward0>)

In [ ]:
loss_f = T.nn.MSELoss()
loss = 0
for i in range(len(pred)):
    loss = loss + loss_f(pred[i],T.tensor(label[i])).item()

print(loss/len(pred))

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/loss.py:520: UserWarning: Using a target size (torch.Size([])) that is different to the input size (torch.Size([1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


0.025681582775023897
